---

version: 0.2

phases:
  build:
    commands:
      - . $CODEBUILD_SRC_DIR/metadata.txt
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_VERSION .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_VERSION megah3rtz/$IMAGE_REPO_NAME:$IMAGE_VERSION

